"""add dismiss field

Revision ID: 0da23d9e1bd0
Revises: 79eea4b92004
Create Date: 2023-08-21 09:57:28.024366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da23d9e1bd0'
down_revision = '79eea4b92004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ig_posts', sa.Column('dismiss', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ig_posts', 'dismiss')
    # ### end Alembic commands ###
