"""change id type from int to str(255)

Revision ID: 0fef7563b436
Revises: 8a09279e73fe
Create Date: 2023-08-16 18:20:27.086027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fef7563b436'
down_revision = '8a09279e73fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
