"""add dismiss field

Revision ID: 149221c4af63
Revises: 0da23d9e1bd0
Create Date: 2023-08-21 10:39:30.546265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149221c4af63'
down_revision = '0da23d9e1bd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
