"""add field url

Revision ID: 79eea4b92004
Revises: 0fef7563b436
Create Date: 2023-08-16 18:23:25.746880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79eea4b92004'
down_revision = '0fef7563b436'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ig_posts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=1000), nullable=False),
    sa.Column('displayUrl_hosted', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('correction_results', sa.String(length=1000), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('saved_ig_posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_ig_posts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('caption', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('displayUrl_hosted', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('correction_results', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('helpful', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ig_posts')
    # ### end Alembic commands ###
