"""add columns created_by,updated_by,created_at,updated_at

Revision ID: 84b9c79ee8fe
Revises: d2211ddcb4f5
Create Date: 2023-09-06 10:54:28.203872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b9c79ee8fe'
down_revision = 'd2211ddcb4f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ig_posts', sa.Column('created_by', sa.String(length=20), nullable=False))
    op.add_column('ig_posts', sa.Column('updated_by', sa.String(length=20), nullable=False))
    op.add_column('ig_posts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ig_posts', 'created_at')
    op.drop_column('ig_posts', 'updated_by')
    op.drop_column('ig_posts', 'created_by')
    # ### end Alembic commands ###
