"""split fullname to first and last name

Revision ID: 9aaed23990ab
Revises: 6e5a95a22acd
Create Date: 2023-07-30 19:57:57.552852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9aaed23990ab'
down_revision = '6e5a95a22acd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('Last_name', sa.String(length=20), nullable=False))
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('users', sa.Column('phone', mysql.VARCHAR(length=13), nullable=True))
    op.drop_column('users', 'Last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
