"""add extensionid column

Revision ID: d2211ddcb4f5
Revises: cb1223fa0bd6
Create Date: 2023-09-05 14:18:37.987661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2211ddcb4f5'
down_revision = 'cb1223fa0bd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ig_posts', sa.Column('extensionId', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ig_posts', 'extensionId')
    # ### end Alembic commands ###
